apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-green
  labels:
    app: order
    version: green    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
      version: green      
  template:
    metadata:
      labels:
        app: order
        version: green        
    spec:
      containers:
        - name: order-green
          image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/shop/order:2.0.0
          imagePullPolicy: Always          
          ports:
            - containerPort: 8080