apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-blue
  labels:
    app: webshop-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop-blue
  template:
    metadata:
      labels:
        app: webshop-blue
    spec:
      containers:
        - name: webshop-blue
          image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/shop/shop:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: URL_PREFIX
              value: "webshop" 
            - name: URL_SUFFIX
              value: "-blue"               
  

                  