apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop
  labels:
    app: webshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop
  template:
    metadata:
      labels:
        app: webshop
    spec:
      containers:
        - name: webshop
          image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/shop/shop:3.0.0
          imagePullPolicy: Always          
          ports:
            - containerPort: 8080
          env:
            - name: URL_PREFIX
              value: "webshop"
            - name: URL_SUFFIX
              value: ""                
  

                  