apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: invoicing
  name: invoicing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: invoicing
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: invoicing
    spec:
      containers:
        - image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/backoffice/invoicing:3.2.0
          name: invoicing
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
