apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sales
  name: sales
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sales
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: sales
    spec:
      containers:
        - env:
            - name: URL_SUFFIX
          image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/management/sales:3.2.0
          name: sales
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"              
      restartPolicy: Always
