apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: shipment
  name: shipment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipment
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: shipment
    spec:
      containers:
        - image: registry.gitlab.com/ch-mc-b/autoshop-ms/app/backoffice/shipment:3.2.0
          name: shipment
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "25m"
              memory: "96Mi"
            limits:
              cpu: "50m"
              memory: "192Mi"              
      restartPolicy: Always
