apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webshop 
  labels:
    app: webshop 
spec:
  rules:
  - http:
      paths:
      - path: /webshop
        pathType: Prefix
        backend:
          service:
            name: webshop
            port:
              number: 8080
                  